#!/usr/bin/env bash
# Bash script that configs SSH

# Set the configuration parameters
PRIVATE_KEY_PATH="$HOME/.ssh/school"
SSH_CONFIG_PATH="$HOME/.ssh/config"

# Ensure the .ssh directory exists
mkdir -p "$HOME/.ssh"

# Create or update SSH configuration
{
    echo "Host *"
    echo "  PasswordAuthentication no"
    echo "  IdentityFile ~/.ssh/school"
} > "$HOME/.ssh/config"

# Update permissions for the private key
chmod 600 "$HOME/.ssh/school"

echo "SSH configuration updated and permissions set for $HOME/.ssh/school"

